apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: nginx-qa
  namespace: nginx
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: qa
