---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: edge
  namespace: edge
spec:
  type: GitHub
  pathname: https://github.com/masanara/acm-example.git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: edge-app
  namespace: edge
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - edge-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: edge-app
  namespace: edge
  labels:
    app: edge-app
  annotations:
    apps.open-cluster-management.io/github-path: resources/edge
spec:
  channel: edge/edge
  placement:
    placementRef:
      kind: PlacementRule
      name: edge
