apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: edge
  namespace: edge
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      cluster_type: edge
